#server configuration
server:
    address: 0.0.0.0
    port: ${appServerPort}
cxf:
    path: /rest

#kie server configuration and capabilities
kieserver:
    serverId: ${artifactId}
    serverName: ${artifactId}
    location: http://${appServerAddress}:${appServerPort}/rest/server
KIE_SERVER_CAPABILITIES_MARKER

JBPM_CONFIG_MARKER

#data source and tx manager configuration
spring:
    datasource:
        username: jbpm
        password: jbpm
        url: jdbc:mysql://localhost:3306/jbpm
        driver-class-name: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                hbm2ddl:
                    auto: update
                show_sql: false
    jta:
        narayana:
            transaction-manager-id: 1


    #banner config
    banner:
            location: classpath:banner.txt